# Generated by Django 4.2.4 on 2023-08-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='torque',
        ),
    ]
