# Generated by Django 4.2.4 on 2023-08-24 10:15

import car.models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('car', '0002_remove_carspecs_torque'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_size', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء'), ('hybrid', 'هايبرد'), ('mild-hybrid', 'مايلد هايبرد'), ('plugin-hybrid', 'هايبرد - plugin')], max_length=20)),
                ('transmission_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('horse_power', models.PositiveIntegerField(blank=True, null=True)),
                ('speed', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fuel_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('Odometer', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('excelent', 'ممتازة'), ('good', 'جيد'), ('small-accident', 'حادث بسيط'), ('accident', 'تعرضت لحادث'), ('other', 'أخرى')], max_length=20)),
                ('custom', models.CharField(choices=[('yes', 'مجمرك'), ('no', 'غير مجمرك')], max_length=20)),
                ('body_type', models.CharField(choices=[('bus', 'Bus'), ('convertible', 'Convertible'), ('Coupe', 'coupe'), ('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pick-up', 'PickUp'), ('truck', 'Truck')], max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('interior', models.TextField(blank=True, null=True)),
                ('interior_image', models.ImageField(upload_to='interior')),
                ('exterior', models.TextField(blank=True, null=True)),
                ('exterior_image', models.ImageField(upload_to='exterior')),
                ('performance', models.CharField(max_length=50)),
                ('performance_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carspecs',
            name='car',
        ),
        migrations.RemoveField(
            model_name='features',
            name='car',
        ),
        migrations.RemoveField(
            model_name='otherinfo',
            name='car',
        ),
        migrations.RemoveField(
            model_name='otherinfo',
            name='maintenance_centers',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='techandsafetyfeatures',
            name='car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
        migrations.DeleteModel(
            name='CarSpecs',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='OtherInfo',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_specs', to='car.car'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='maintenance_centers',
            field=models.ManyToManyField(blank=True, default=None, related_name='maintenance_centers', to='maintenance.maintenancecenter'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='car.tag'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='tech_and_safety_features',
            field=models.ManyToManyField(related_name='cars', to='car.techandsafetyfeatures'),
        ),
    ]
