# Generated by Django 4.2.4 on 2023-08-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_cardetails_remove_carspecs_car_remove_features_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='engine_size',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
