# Generated by Django 4.2.4 on 2023-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('car', '0004_remove_cardetails_engine_size_car_engine_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='car',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='maintenance_centers',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='tech_and_safety_features',
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='valid_release_year',
        ),
        migrations.AddField(
            model_name='car',
            name='Odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('convertible', 'Convertible'), ('Coupe', 'coupe'), ('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pick-up', 'PickUp'), ('truck', 'Truck')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, choices=[('excelent', 'ممتازة'), ('good', 'جيد'), ('small-accident', 'حادث بسيط'), ('accident', 'تعرضت لحادث'), ('other', 'أخرى')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='custom',
            field=models.CharField(blank=True, choices=[('yes', 'مجمرك'), ('no', 'غير مجمرك')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='exterior'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء'), ('hybrid', 'هايبرد'), ('mild-hybrid', 'مايلد هايبرد'), ('plugin-hybrid', 'هايبرد - plugin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='horse_power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='interior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to='interior'),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_centers',
            field=models.ManyToManyField(blank=True, default=None, related_name='maintenance_centers', to='maintenance.maintenancecenter'),
        ),
        migrations.AddField(
            model_name='car',
            name='performance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='performance_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='car.tag'),
        ),
        migrations.AddField(
            model_name='car',
            name='tech_and_safety_features',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='car.techandsafetyfeatures'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('release_year__gte', 1900), ('release_year__lte', 2025)), name='valid_release_year'),
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
