# Generated by Django 4.2.4 on 2023-08-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_cardetails_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='car.car'),
        ),
    ]
