# Generated by Django 4.2.4 on 2023-08-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_rename_features_techandsafetyfeatures_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, related_name='tags', to='car.tag'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tech_and_safety_features',
            field=models.ManyToManyField(blank=True, default=None, related_name='cars', to='car.techandsafetyfeatures'),
        ),
    ]
