# Generated by Django 4.2.4 on 2023-08-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_tags_alter_car_tech_and_safety_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='tags', to='car.tag'),
        ),
    ]
