# Generated by Django 4.2.4 on 2023-08-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_car_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='exterior/<django.db.models.fields.CharField>/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to='interior/<django.db.models.fields.CharField>/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
