# Generated by Django 4.2.4 on 2023-08-26 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_car_exterior_image_alter_car_interior_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='exterior/<django.db.models.fields.UUIDField>'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to='interior/<django.db.models.fields.UUIDField>'),
        ),
    ]
