# Generated by Django 4.2.4 on 2023-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_exterior_image_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='exterior/<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to='interior/<built-in function id>'),
        ),
    ]
