# Generated by Django 4.2.4 on 2023-08-26 01:30

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_alter_car_exterior_image_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.car_image_exterior_path),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.car_image_interior_path),
        ),
    ]
