# Generated by Django 4.2.4 on 2023-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pick-up', 'PickUp'), ('truck', 'Truck')], max_length=20, null=True),
        ),
    ]
