# Generated by Django 4.2.4 on 2023-08-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_alter_car_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='car.car'),
        ),
    ]
