# Generated by Django 4.2.4 on 2023-08-28 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_car_description_car_liked_by_car_post_time_car_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('lightgray', 'Lightgray'), ('darkgray', 'Darkgray'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('gold', 'Gold')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
    ]
