# Generated by Django 4.2.4 on 2023-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_alter_car_color_alter_car_post_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to='car_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='exterior_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interior_image',
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_image',
            field=models.ManyToManyField(blank=True, related_name='exterior_images', to='car.imagemodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_image',
            field=models.ManyToManyField(blank=True, related_name='interior_images', to='car.imagemodel'),
        ),
    ]
