# Generated by Django 4.2.4 on 2023-08-30 09:03

import car.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_imagemodel_remove_car_exterior_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='exterior_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interior_image',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_field',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to=car.utils.car_image_exterior_path),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to=car.utils.car_image_interior_path),
        ),
    ]
