# Generated by Django 4.2.4 on 2023-08-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0022_remove_car_exterior_image_remove_car_interior_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car'),
        ),
    ]
