# Generated by Django 4.2.4 on 2023-08-30 09:47

import car.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_alter_imagemodel_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_image', models.ImageField(blank=True, null=True, upload_to=car.utils.car_image_exterior_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_images', to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to=car.utils.car_image_interior_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='car.car')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
