# Generated by Django 4.2.4 on 2023-08-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0025_remove_review_like_carlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='liked_by',
        ),
    ]
