# Generated by Django 4.2.4 on 2023-08-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0026_remove_car_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarLike',
        ),
    ]
