# Generated by Django 4.2.4 on 2023-09-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0027_delete_carlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Chevrolet', 'Chevrolet'), ('Cadillac', 'Cadillac'), ('Acura', 'Acura'), ('BMW', 'BMW'), ('Chrysler', 'Chrysler'), ('Ford', 'Ford'), ('Buick', 'Buick'), ('INFINITI', 'INFINITI'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Genesis', 'Genesis'), ('Dodge', 'Dodge'), ('Jaguar', 'Jaguar'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Lincoln', 'Lincoln'), ('MAZDA', 'MAZDA'), ('Nissan', 'Nissan'), ('MINI', 'MINI'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Subaru', 'Subaru'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Alfa Romeo', 'Alfa Romeo'), ('FIAT', 'FIAT'), ('Freightliner', 'Freightliner'), ('Maserati', 'Maserati'), ('Tesla', 'Tesla'), ('Aston Martin', 'Aston Martin'), ('Bentley', 'Bentley'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Lotus', 'Lotus'), ('McLaren', 'McLaren'), ('Rolls-Royce', 'Rolls-Royce'), ('smart', 'smart'), ('Scion', 'Scion'), ('SRT', 'SRT'), ('Suzuki', 'Suzuki'), ('Fisker', 'Fisker'), ('Maybach', 'Maybach'), ('Mercury', 'Mercury'), ('Saab', 'Saab'), ('HUMMER', 'HUMMER'), ('Pontiac', 'Pontiac'), ('Saturn', 'Saturn'), ('Isuzu', 'Isuzu'), ('Panoz', 'Panoz'), ('Oldsmobile', 'Oldsmobile'), ('Daewoo', 'Daewoo'), ('Plymouth', 'Plymouth'), ('Eagle', 'Eagle'), ('Geo', 'Geo'), ('Daihatsu', 'Daihatsu'), ('Polestar', 'Polestar'), ('Rivian', 'Rivian'), ('Opel', 'Opel')], max_length=50),
        ),
    ]
