# Generated by Django 4.2.4 on 2023-08-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0026_remove_car_liked_by'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_cars',
            field=models.ManyToManyField(related_name='favorited_by', to='car.car'),
        ),
    ]
