# Generated by Django 4.2.4 on 2023-09-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_favorite_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorite_cars',
            new_name='favorite_posts',
        ),
    ]
