# Generated by Django 4.2.4 on 2023-09-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
