# Generated by Django 4.2.4 on 2023-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_articles', '0001_initial'),
        ('user', '0004_rename_favorite_posts_profile_favorite_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_posts',
            field=models.ManyToManyField(related_name='favorited_by', to='news_and_articles.newsandarticles'),
        ),
    ]
