# Generated by Django 4.2.4 on 2023-09-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='num_posts',
        ),
    ]
