# Generated by Django 4.2.4 on 2023-09-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecenter',
            name='brand',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bentley', 'Bentley'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Daewoo', 'Daewoo'), ('Daihatsu', 'Daihatsu'), ('Dodge', 'Dodge'), ('Eagle', 'Eagle'), ('FIAT', 'FIAT'), ('Ferrari', 'Ferrari'), ('Fisker', 'Fisker'), ('Ford', 'Ford'), ('Freightliner', 'Freightliner'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Geo', 'Geo'), ('HUMMER', 'HUMMER'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('INFINITI', 'INFINITI'), ('Isuzu', 'Isuzu'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('MAZDA', 'MAZDA'), ('MINI', 'MINI'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mercury', 'Mercury'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Oldsmobile', 'Oldsmobile'), ('Opel', 'Opel'), ('Panoz', 'Panoz'), ('Plymouth', 'Plymouth'), ('Polestar', 'Polestar'), ('Pontiac', 'Pontiac'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Rivian', 'Rivian'), ('Rolls-Royce', 'Rolls-Royce'), ('SRT', 'SRT'), ('Saab', 'Saab'), ('Saturn', 'Saturn'), ('Scion', 'Scion'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('smart', 'smart')], max_length=50, null=True),
        ),
    ]
