# Generated by Django 4.2.4 on 2023-09-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandarticles',
            name='liked_by',
        ),
    ]
