# Generated by Django 4.2.4 on 2023-09-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('news_and_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandarticlesreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewd_by', to='user.profile'),
        ),
        migrations.AddField(
            model_name='newsandarticles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.profile'),
        ),
    ]
