# Generated by Django 4.2.4 on 2023-09-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_articles', '0002_remove_newsandarticles_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandarticlesreview',
            name='like',
        ),
    ]
